import { ELoadEvents } from '../../gameLib/Loader';
import Scene from '../../gameLib/Scene';
import { setLoadedGame } from '../../store/slices/game';
import store from '../../store/store';

export default class LoaderScene extends Scene{
  constructor(){
    super('LoadScene');
  }

  preload(){
    const graphicsFon = this.add.graphics();
    graphicsFon.fillStyle('#000');
    graphicsFon.fillRect(0,0,this.width,this.height);
    const graphics = this.add.graphics();
    const text = this.add.text('Loading...', this.halfWidth-30, this.halfHeight-40);
    text.color = 'white';
    this.load.on(ELoadEvents.progress, (value)=>{
      graphics.fillStyle('#ffffff');
      graphics.fillRect(0,this.halfHeight,this.width*value,20);
    });
    graphics.fillStyle('#ffffff');
    graphics.fillRect(0,0,0,20);

    this.load.image('ship-body-type-4', './assets/ship-body-type-4.png');
    this.load.image('ship-detail-type-4', './assets/ship-detail-type-4.png');
    this.load.image('ship-body-type-3', './assets/ship-body-type-3.png');
    this.load.image('ship-detail-type-3', './assets/ship-detail-type-3.png');
    this.load.image('ship-body-type-2', './assets/ship-body-type-2.png');
    this.load.image('ship-detail-type-2', './assets/ship-detail-type-2.png');
    this.load.image('ship-body-type-1', './assets/ship-body-type-1.png');
    this.load.image('ship-detail-type-1', './assets/ship-detail-type-1.png');

    this.load.image('gun-body-type-3', './assets/gun-body-type-4.png');
    this.load.image('gun-detail-type-3', './assets/gun-detail-type-4.png');
    this.load.image('gun-body-type-2', './assets/gun-body-type-2.png');
    this.load.image('gun-detail-type-2', './assets/gun-detail-type-2.png');
    this.load.image('gun-body-type-1', './assets/gun-body-type-1.png');
    this.load.image('gun-detail-type-1', './assets/gun-detail-type-1.png');
    
    this.load.image('shipyard', './assets/shipyard.png');
    this.load.image('shipyard2', './assets/shipyard2.png');
    this.load.image('cursor-target', './assets/cursor-target.png');
    this.load.image('shot-cell', './assets/shot-cell.png');
    this.load.image('shot-cell-ship', './assets/shot-cell-ship.png');
    this.load.image('bullet', './assets/bullet.png');
    this.load.image('zebra', './assets/zebra.png');
    this.load.image('pixel', './assets/pixel.png');
    this.load.spritesheet('explosion', 'assets/explosion.png', { frameWidth: 64, frameHeight: 64, endFrame: 23 });
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
    // this.load.image('first', './assets/logo512.png');
    // this.load.image('second', './assets/fon2.png');
  }

  create(){
    //console.log('complate loaded scene!!!');
    store.dispatch(setLoadedGame());
    //this.add.sprite('second');
    //this.add.sprite('first', 10,0, 40);
    //this.scene.start('Shipyard');
    //this.scene.start('MainScene');
  }
}